version: '3'

services:
  node:
    image: node:19.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/api/
    ports:
      - 3000:3000
    volumes:
      - ./api:/home/api/
    command:
      - sh
      - -c
      - |
        npm install
        npm run start:dev
  # npm i @nestjs/cli --save-dev
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      - POSTGRES_DB=app
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
